# Matrix
---
Under this section, we will learn about :

1. Matrix Building Functions
2. Advance Matrix Creation
3. Subsetting of Matrix
4. Scalar Operation on Matrices
5. Matrix Operations

## Matrix Building Functions :
---
In MATLAB, we have some matrix building functions using which we can create some special kind of matrices, as follows :

1. `ones()`: Creates a matrix with each element as `1`.
1. `zeros()`: Creates a matrix with each element as `0`.
1. `repmat()`: Creates a matrix with each element as a constant number.
1. `eye()`: Creates an identity matrix.
1. `rand()`: Creating a matrix of random numbers.
1. `randn()`: Creating a matrix of gaussian distributed random numbers.
1. `magic()`: Creating a magic square matrix
1. `hilb()`: Creating a Hilbert's matrix
1. `diag()`: Creating a diagonal matrix or, extracting the diagonal elements of a matrix.

Now, let's see some examples of the above matrix building functions.

#### `ones()`:

Create a `(3 x 4)` matrix with all the elements as `1` :

In [1]:
ones(3,4)

ans =

   1   1   1   1
   1   1   1   1
   1   1   1   1



We can also use the `ones()` function to create a matrix with all the elements as `n` (where `n` can be any real number).

***For example :*** Creating a `(4 x 5)` matrix with all the elements as `2.53` :

In [2]:
2.53 * ones(4,5)

ans =

   2.5300   2.5300   2.5300   2.5300   2.5300
   2.5300   2.5300   2.5300   2.5300   2.5300
   2.5300   2.5300   2.5300   2.5300   2.5300
   2.5300   2.5300   2.5300   2.5300   2.5300



#### `zeros()`:
Create a `(5 x 5)` matrix with all the elements as `0` :

In [3]:
zeros(5)

ans =

   0   0   0   0   0
   0   0   0   0   0
   0   0   0   0   0
   0   0   0   0   0
   0   0   0   0   0



similarly, to create a `(2 x 3)` matrix with all the elements as `0` :

In [4]:
zeros(2,3)

ans =

   0   0   0
   0   0   0



#### `repmat()`
Crete a `(3 x 5)`matrix with all the elements as `2.5` :

In [5]:
repmat(2.5,3,5)

ans =

   2.5000   2.5000   2.5000   2.5000   2.5000
   2.5000   2.5000   2.5000   2.5000   2.5000
   2.5000   2.5000   2.5000   2.5000   2.5000



In the above code, the first argument is the constant element, the 2nd argument is the row size and the 3rd argument is the column size.

##### `eye()`:
An identity matrix is a square matrix with diagonal elements as `1`.
To create a `(4 x 4)` identity matrix :

In [7]:
eye(4)

ans =

Diagonal Matrix

   1   0   0   0
   0   1   0   0
   0   0   1   0
   0   0   0   1



If we want all the `1` in the off-diagonal then, we can use the following command :

In [8]:
flipud(eye(4))

ans =

Permutation Matrix

   0   0   0   1
   0   0   1   0
   0   1   0   0
   1   0   0   0



##### `rand()`:
Create a `(3 x 3)` square matrix of randomly generated numbers :

In [10]:
rand(3)

ans =

   0.90835   0.78690   0.40332
   0.65284   0.32649   0.11322
   0.23244   0.84265   0.64247



Similarly, we can create a `(3 x 2)` matrix of randomly generated numbers as follows :

In [11]:
rand(3,2)

ans =

   0.583355   0.851566
   0.745667   0.857796
   0.095037   0.578485



> ***Note :***<br>
The `rand()` function generates positive decimal numbers between `0` to `1` and we can perform various arithmetic operations to get bigger numbers out of it.

Creating a `(4 x 3)` matrix with randomly generated numbers between greater than `1`

In [13]:
1000 * rand(4,3)

ans =

   381.371   482.617    60.746
   399.747   330.076   429.968
   967.202    68.228    60.274
    11.573   600.263   724.278



##### `randn()`:
The function `randn()` is very much similar to the function `rand()`, but, it generates gaussian distributed numbers.

So, to create a `R5` vector (column matrix) of gaussian distributed numbers :

In [15]:
randn(5,1)

ans =

  -0.705755
  -0.163149
   0.522345
  -0.153358
   0.029000



##### `magic ()`:

The function `magic ()` generates a **sqare matrix** such that, the summation of all the elements of each row, each column and each diagonal is same.

A magic matrix needs can be of atleast ($3 \times 3$) dimension.

To create a magic matrix of ($5 \times 5$) :

In [16]:
magic(5)

ans =

   17   24    1    8   15
   23    5    7   14   16
    4    6   13   20   22
   10   12   19   21    3
   11   18   25    2    9



##### `hilb ()`:

The `hilb ()` is used to create a Hilbert's matrix.

A Hilbert's matrix is a **square matrix** with elements as : $\frac{1}{(i+j-1)}\$

Where,<br>
 $i$ : Row Number<br>
 $j$ : Column Number

 To create a Hilbert's matrix of ($4 \times 4$) order :

In [17]:
hilb(4)

ans =

   1.00000   0.50000   0.33333   0.25000
   0.50000   0.33333   0.25000   0.20000
   0.33333   0.25000   0.20000   0.16667
   0.25000   0.20000   0.16667   0.14286



##### `diag ()`:
The function `diag()` can be used to create a diagonal matrix of certain elements by using a vector, as follows :

In [18]:
% First we need to create a vector of elements to be taken as diagonal element :

vec = [53;65;43;45];

% Now, we can use the `diag()` function as follows :

diag(vec)

ans =

Diagonal Matrix

   53    0    0    0
    0   65    0    0
    0    0   43    0
    0    0    0   45



Now, if we want the vector elements in the off-diagonal, then, we can simply use the `flipud()` function along with `diag()`, as follows :

In [19]:
flipud(diag(vec))

ans =

    0    0    0   45
    0    0   43    0
    0   65    0    0
   53    0    0    0



`diag()` can also be used to extract the diagonal & off-diagonal elements of a matrix as follows :

In [21]:
% Create a (5 x 5) matrix :
mat = rand(5)

% Extract the diagonal elements :
diag(mat)

% Extract off-diagonal elements :
diag( flipud(mat) )

mat =

   0.5467739   0.8401000   0.8548301   0.3112132   0.8588380
   0.1917042   0.5565096   0.7436879   0.4590984   0.4700677
   0.7685720   0.5212827   0.0630870   0.5055235   0.4214928
   0.0085219   0.5035706   0.3175891   0.2234724   0.3974079
   0.4880584   0.8505889   0.3448342   0.1701311   0.3251142

ans =

   0.546774
   0.556510
   0.063087
   0.223472
   0.325114

ans =

   0.488058
   0.503571
   0.063087
   0.459098
   0.858838



## Advance Matrix Creation
---
Other than using matrix building functions or, typing out numbers manually; we can actually create matrix from other pre-existing matrices or, by combining arrays/vectors.

But, while performing such advance matrix creating methods, we have to give a special attention towards the dimension of the matrices that we are taking into account otherwise, we may end-up in getting an error message.

Now, let's create a matrix using a vector and an identity matrix :