# Matrix
---
Under this section, we will learn about :

1. Matrix Building Functions
2. Advance Matrix Creation
3. Subsetting of Matrix
4. Scalar Operation on Matrices
5. Matrix Operations

## Matrix Building Functions :
---
In MATLAB, we have some matrix building functions using which we can create some special kind of matrices, as follows :

1. `ones()`: Creates a matrix with each element as `1`.
1. `zeros()`: Creates a matrix with each element as `0`.
1. `repmat()`: Creates a matrix with each element as a constant number.
1. `eye()`: Creates an identity matrix.
1. `rand()`: Creating a matrix of random numbers.
1. `randn()`: Creating a matrix of gaussian distributed random numbers.
1. `magic()`: Creating a magic square matrix
1. `hilb()`: Creating a Hilbert's matrix
1. `diag()`: Creating a diagonal matrix or, extracting the diagonal elements of a matrix.

Now, let's see some examples of the above matrix building functions.

#### `ones()`:

Create a $(3 \times 4)$ matrix with all the elements as `1` :

In [1]:
ones(3,4)

ans =

   1   1   1   1
   1   1   1   1
   1   1   1   1



We can also use the `ones()` function to create a matrix with all the elements as $n$ (where $n$ can be any real number).

***For example :*** Creating a $(4 \times 5)$ matrix with all the elements as $2.53$ :

In [2]:
2.53 * ones(4,5)

ans =

   2.5300   2.5300   2.5300   2.5300   2.5300
   2.5300   2.5300   2.5300   2.5300   2.5300
   2.5300   2.5300   2.5300   2.5300   2.5300
   2.5300   2.5300   2.5300   2.5300   2.5300



#### `zeros()`:
Create a $(5 \times 5)$ matrix with all the elements as $0$ :

In [3]:
zeros(5)

ans =

   0   0   0   0   0
   0   0   0   0   0
   0   0   0   0   0
   0   0   0   0   0
   0   0   0   0   0



similarly, to create a $(2 \times 3)$ matrix with all the elements as $0$ :

In [4]:
zeros(2,3)

ans =

   0   0   0
   0   0   0



#### `repmat()`
Crete a $(3 x 5)$matrix with all the elements as $2.5$:

In [5]:
repmat(2.5,3,5)

ans =

   2.5000   2.5000   2.5000   2.5000   2.5000
   2.5000   2.5000   2.5000   2.5000   2.5000
   2.5000   2.5000   2.5000   2.5000   2.5000



In the above code, the first argument is the constant element, the 2nd argument is the row size and the 3rd argument is the column size.

##### `eye()`:
An identity matrix is a **square matrix** with diagonal elements as $1$.<br>
To create a $(4 \times 4)$ identity matrix :

In [6]:
eye(4)

ans =

Diagonal Matrix

   1   0   0   0
   0   1   0   0
   0   0   1   0
   0   0   0   1



If we want all the $1$ in the off-diagonal then, we can use the following command :

In [7]:
flipud(eye(4))

ans =

Permutation Matrix

   0   0   0   1
   0   0   1   0
   0   1   0   0
   1   0   0   0



##### `rand()`:
Create a $(3 \times 3)$ square matrix of randomly generated numbers :

In [8]:
rand(3)

ans =

   0.447843   0.149666   0.028738
   0.262075   0.404148   0.124025
   0.251250   0.435023   0.817570



Similarly, we can create a $(3 \times 2)$ matrix of randomly generated numbers as follows :

In [9]:
rand(3,2)

ans =

   0.64217   0.90769
   0.79599   0.27838
   0.59834   0.10790



> ***Note :***<br>
The `rand()` function generates positive decimal numbers between $0$ to $1$ and we can perform various arithmetic operations to get bigger numbers out of it.

Creating a $(4 \times 3)$ matrix with randomly generated numbers between greater than $1$

In [10]:
1000 * rand(4,3)

ans =

   650.60   384.76   568.58
   698.82   413.31   716.10
   955.98   694.88   554.41
   178.47   732.65   784.14



##### `randn()`:
The function `randn()` is very much similar to the function `rand()`, but, it generates gaussian distributed numbers.

So, to create a $R^5$ vector (column matrix) of gaussian distributed numbers :

In [11]:
randn(5,1)

ans =

  -0.017530
   0.121510
   0.582453
  -0.157294
   0.690301



##### `magic ()`:

The function `magic ()` generates a **sqare matrix** such that, the summation of all the elements of each row, each column and each diagonal is same.

A magic matrix needs can be of atleast ($3 \times 3$) dimension.

To create a magic matrix of ($5 \times 5$) :

In [12]:
magic(5)

ans =

   17   24    1    8   15
   23    5    7   14   16
    4    6   13   20   22
   10   12   19   21    3
   11   18   25    2    9



##### `hilb ()`:

The `hilb ()` is used to create a Hilbert's matrix.

A Hilbert's matrix is a **square matrix** with elements as : $\frac{1}{(i+j-1)}\$

Where,<br>
 $i$ : Row Number<br>
 $j$ : Column Number

 To create a Hilbert's matrix of ($4 \times 4$) order :

In [13]:
hilb(4)

ans =

   1.00000   0.50000   0.33333   0.25000
   0.50000   0.33333   0.25000   0.20000
   0.33333   0.25000   0.20000   0.16667
   0.25000   0.20000   0.16667   0.14286



##### `diag ()`:
The function `diag()` can be used to create a diagonal matrix of certain elements by using a vector, as follows :

In [14]:
% First we need to create a vector of elements to be taken as diagonal element :

vec = [53;65;43;45];

% Now, we can use the `diag()` function as follows :

diag(vec)

ans =

Diagonal Matrix

   53    0    0    0
    0   65    0    0
    0    0   43    0
    0    0    0   45



Now, if we want the vector elements in the off-diagonal, then, we can simply use the `flipud()` function along with `diag()`, as follows :

In [15]:
flipud(diag(vec))

ans =

    0    0    0   45
    0    0   43    0
    0   65    0    0
   53    0    0    0



`diag()` can also be used to extract the diagonal & off-diagonal elements of a matrix as follows :

In [16]:
% Create a (5 x 5) matrix :
mat = rand(5)

% Extract the diagonal elements :
diag(mat)

% Extract off-diagonal elements :
diag( flipud(mat) )

mat =

   0.746177   0.618413   0.800590   0.121924   0.071330
   0.635075   0.192364   0.443051   0.228145   0.470675
   0.980789   0.619980   0.169974   0.217161   0.656082
   0.742239   0.325528   0.844373   0.083955   0.767166
   0.063329   0.768727   0.015409   0.699457   0.389655

ans =

   0.746177
   0.192364
   0.169974
   0.083955
   0.389655

ans =

   0.063329
   0.325528
   0.169974
   0.228145
   0.071330



## Advance Matrix Creation
---
Other than using matrix building functions or, typing out numbers manually; we can actually create matrix from other pre-existing matrices or, by combining arrays/vectors.

But, while performing such advance matrix creating methods, we have to give a special attention towards the dimension of the matrices that we are taking into account otherwise, we may end-up in getting an error message.

Now, let's create a matrix using a vector and an identity matrix :

In [17]:
% Creating a vector :

v = [20; 40; 50; 70]

% Creating an identity matrix

I = eye(4)

% Adding 'v' as a column to 'I' to create a (4 x 5) matrix

P = [v,I]

v =

   20
   40
   50
   70

I =

Diagonal Matrix

   1   0   0   0
   0   1   0   0
   0   0   1   0
   0   0   0   1

P =

   20    1    0    0    0
   40    0    1    0    0
   50    0    0    1    0
   70    0    0    0    1



Now, let's create an array and then use it with the previously created identity matrix `I` to create another matrix

In [18]:
% Creating an array :
a = [1,2,3,4]

% Appending 'a' over the identity matrix 'I' to form a (5 x 4) matrix
Q = [a; I]

a =

   1   2   3   4

Q =

   1   2   3   4
   1   0   0   0
   0   1   0   0
   0   0   1   0
   0   0   0   1



## Sub-setting of Matrix

---

Let's create a $(4 \times 6)$ matrix for performing various sub-setting operation :

In [19]:
matrx = [
24,52,66,85,15,79;
44,57,53,40,47,72;
38,66,69,86,25,82;
36,73,76,72,28,91]

matrx =

   24   52   66   85   15   79
   44   57   53   40   47   72
   38   66   69   86   25   82
   36   73   76   72   28   91



In [20]:
% To extract only the 1st row :

matrx(1,:)

ans =

   24   52   66   85   15   79



In [21]:
% To extract only the 3rd column :

matrx(:,3)

ans =

   66
   53
   69
   76



In [22]:
% To extract a square matrix using last two rows and 1st two columns :

matrx(3:4,1:2)

ans =

   38   66
   36   73



In [23]:
% To extract a square matrix using the 2nd & 4th row with 4th & 6th column :

matrx([2,4],[4,6])

ans =

   40   72
   72   91



In [24]:
% To extract the element preset at 3rd row and 6th column :

matrx(3,6)

ans =  82


## Scalar Operation on Matrices

---

All the mathematical operations that we have performed with individual numbers/variables can also be applied to matrices.

So, if we have `(4 x 4)` matrix and we enclose it within a `log()` function then, in the resultant matrix, we will get logarithm of each element.

Let's perform the scalar operations upon the previously created $(4 \times 6)$ matrix assigned to the variable `matrx` :

In [25]:
% Viewing the 'matrx'

matrx

matrx =

   24   52   66   85   15   79
   44   57   53   40   47   72
   38   66   69   86   25   82
   36   73   76   72   28   91



#### Arithmetic Operations :

In [26]:
% Scalar addition
Scalar_add = 2.5 + matrx

Scalar_add =

   26.500   54.500   68.500   87.500   17.500   81.500
   46.500   59.500   55.500   42.500   49.500   74.500
   40.500   68.500   71.500   88.500   27.500   84.500
   38.500   75.500   78.500   74.500   30.500   93.500



In [27]:
% Scalar subtraction
Scalar_subs = 2.5 - matrx

Scalar_subs =

  -21.500  -49.500  -63.500  -82.500  -12.500  -76.500
  -41.500  -54.500  -50.500  -37.500  -44.500  -69.500
  -35.500  -63.500  -66.500  -83.500  -22.500  -79.500
  -33.500  -70.500  -73.500  -69.500  -25.500  -88.500



In [28]:
% Scalar multiplication
Scalar_mult = 5 * matrx

Scalar_mult =

   120   260   330   425    75   395
   220   285   265   200   235   360
   190   330   345   430   125   410
   180   365   380   360   140   455



In [29]:
% Scalar division
Scalar_div = matrx / 3.5

Scalar_div =

    6.8571   14.8571   18.8571   24.2857    4.2857   22.5714
   12.5714   16.2857   15.1429   11.4286   13.4286   20.5714
   10.8571   18.8571   19.7143   24.5714    7.1429   23.4286
   10.2857   20.8571   21.7143   20.5714    8.0000   26.0000



In [30]:
% Scalar remainder
Scalar_rem = rem (matrx,25)

Scalar_rem =

   24    2   16   10   15    4
   19    7    3   15   22   22
   13   16   19   11    0    7
   11   23    1   22    3   16



In [31]:
% Scalar exponent
Scalar_pow = power(matrx,3)

% or,

Scalar_pow2 = matrx .^ 3

Scalar_pow =

    13824   140608   287496   614125     3375   493039
    85184   185193   148877    64000   103823   373248
    54872   287496   328509   636056    15625   551368
    46656   389017   438976   373248    21952   753571

Scalar_pow2 =

    13824   140608   287496   614125     3375   493039
    85184   185193   148877    64000   103823   373248
    54872   287496   328509   636056    15625   551368
    46656   389017   438976   373248    21952   753571



In [32]:
% Scalar square root
Scalar_sqrt = sqrt (matrx)

Scalar_sqrt =

   4.8990   7.2111   8.1240   9.2195   3.8730   8.8882
   6.6332   7.5498   7.2801   6.3246   6.8557   8.4853
   6.1644   8.1240   8.3066   9.2736   5.0000   9.0554
   6.0000   8.5440   8.7178   8.4853   5.2915   9.5394



#### Logarithimic Operations

In [33]:
% Scalar logarithimic opertaion
Scalar_log = log (matrx)

Scalar_log =

   3.1781   3.9512   4.1897   4.4427   2.7081   4.3694
   3.7842   4.0431   3.9703   3.6889   3.8501   4.2767
   3.6376   4.1897   4.2341   4.4543   3.2189   4.4067
   3.5835   4.2905   4.3307   4.2767   3.3322   4.5109



In [34]:
% Scalar exp operation
Scalar_exp = exp (matrx)

Scalar_exp =

   2.6489e+10   3.8310e+22   4.6072e+28   8.2230e+36   3.2690e+06   2.0383e+34
   1.2852e+19   5.6857e+24   1.0414e+23   2.3539e+17   2.5813e+20   1.8587e+31
   3.1856e+16   4.6072e+28   9.2538e+29   2.2352e+37   7.2005e+10   4.0940e+35
   4.3112e+15   5.0524e+31   1.0148e+33   1.8587e+31   1.4463e+12   3.3174e+39



#### Trigonometric Operations

In [35]:
% Scalar Sine Operation
Scalar_sine = sin(matrx)

Scalar_sine =

  -0.905578   0.986628  -0.026551  -0.176076   0.650288  -0.444113
   0.017702   0.436165   0.395925   0.745113   0.123573   0.253823
   0.296369  -0.026551  -0.114785  -0.923458  -0.132352   0.313229
  -0.991779  -0.676772   0.566108   0.253823   0.270906   0.105988



In [36]:
% Scalar Cosine Operation
Scalar_cosine = cos(matrx)

Scalar_cosine =

   0.42418  -0.16299  -0.99965  -0.98438  -0.75969  -0.89597
   0.99984   0.89987  -0.91828  -0.66694  -0.99234  -0.96725
   0.95507  -0.99965   0.99339  -0.38370   0.99120   0.94968
  -0.12796  -0.73619   0.82433  -0.96725  -0.96261  -0.99437



In [37]:
% Scalar Tangent Operation
Scalar_tangent = tan(matrx)

Scalar_tangent =

  -2.134897  -6.053272   0.026561   0.178870  -0.855993   0.495678
   0.017705   0.484699  -0.431158  -1.117215  -0.124528  -0.262417
   0.310310   0.026561  -0.115549   2.406730  -0.133526   0.329826
   7.750471   0.919286   0.686748  -0.262417  -0.281430  -0.106588



In [38]:
% Scalar Inverse Sine Operation
Scalar_invsin = asin(matrx)

Scalar_invsin =

 Columns 1 through 4:

   1.5708 - 3.8708i   1.5708 - 4.6443i   1.5708 - 4.8827i   1.5708 - 5.1358i
   1.5708 - 4.4772i   1.5708 - 4.7361i   1.5708 - 4.6634i   1.5708 - 4.3819i
   1.5708 - 4.3306i   1.5708 - 4.8827i   1.5708 - 4.9272i   1.5708 - 5.1475i
   1.5708 - 4.2765i   1.5708 - 4.9836i   1.5708 - 5.0238i   1.5708 - 4.9698i

 Columns 5 and 6:

   1.5708 - 3.4001i   1.5708 - 5.0626i
   1.5708 - 4.5432i   1.5708 - 4.9698i
   1.5708 - 3.9116i   1.5708 - 5.0998i
   1.5708 - 4.0250i   1.5708 - 5.2040i



In [39]:
% Scalar Inverse Cosine Operation
Scalar_invcos = acos(matrx)

Scalar_invcos =

 Columns 1 through 4:

   0.0000 + 3.8708i   0.0000 + 4.6443i   0.0000 + 4.8827i   0.0000 + 5.1358i
   0.0000 + 4.4772i   0.0000 + 4.7361i   0.0000 + 4.6634i   0.0000 + 4.3819i
   0.0000 + 4.3306i   0.0000 + 4.8827i   0.0000 + 4.9272i   0.0000 + 5.1475i
   0.0000 + 4.2765i   0.0000 + 4.9836i   0.0000 + 5.0238i   0.0000 + 4.9698i

 Columns 5 and 6:

   0.0000 + 3.4001i   0.0000 + 5.0626i
   0.0000 + 4.5432i   0.0000 + 4.9698i
   0.0000 + 3.9116i   0.0000 + 5.0998i
   0.0000 + 4.0250i   0.0000 + 5.2040i



In [40]:
% Scalar Tangent Operation
Scalar_invtan = atan(matrx)

Scalar_invtan =

   1.5292   1.5516   1.5556   1.5590   1.5042   1.5581
   1.5481   1.5533   1.5519   1.5458   1.5495   1.5569
   1.5445   1.5556   1.5563   1.5592   1.5308   1.5586
   1.5430   1.5571   1.5576   1.5569   1.5351   1.5598



#### Rounding-off Operations

If we have a matrix with decimal values as elements then, we can perform the rounding-off operations over each element.

Let's create a random $(5 \times 5)$ decimal matrix to perform the rounding-off operations

In [41]:
randmat = rand(5)

randmat =

   0.973944   0.138578   0.054543   0.878546   0.661902
   0.150763   0.065829   0.657992   0.471293   0.424776
   0.153990   0.929081   0.978102   0.493937   0.803452
   0.138700   0.478462   0.327101   0.350096   0.428619
   0.652401   0.958826   0.677566   0.774710   0.135738



Now, let's apply the various rounding-off operations over the matrix :

In [42]:
% rounding
rounding = round (randmat)

rounding =

   1   0   0   1   1
   0   0   1   0   0
   0   1   1   0   1
   0   0   0   0   0
   1   1   1   1   0



In [43]:
% Ceiling
ceiling = ceil (randmat)

ceiling =

   1   1   1   1   1
   1   1   1   1   1
   1   1   1   1   1
   1   1   1   1   1
   1   1   1   1   1



In [45]:
% Flooring
flooring = floor (randmat)

flooring =

   0   0   0   0   0
   0   0   0   0   0
   0   0   0   0   0
   0   0   0   0   0
   0   0   0   0   0



## Matrix Operations

---

Now, let's see how we can perform various matrix operation with other matrices. The various matrix operations are :

1. Size of a Matrix
2. Length of a Matrix
3. Reshaping of a Matrix
4. Statistical Operations on a Matrix
5. Arithmetic Operations on a Matrix
6. Logarithmic Operations on a Matrix
7. Exponential Operations on a Matrix
8. Determinant of a Matrix
9. Transpose of a Matrix
10. Inverse of a Matrix
11. Eigen Values & Eigen Vectors of a Matrix
12. Matrix Addition, Subtraction & Multiplication
13. Element-wise Matrix Multiplication & Division

Now, let's create two $(4 \times 4)$ sqare matrix from the previously created $(4 \times 6)$ matrix (assigned to `matrx`) to perform various matrix operations.

In [46]:
% Viewing 'matrx'

matrx

matrx =

   24   52   66   85   15   79
   44   57   53   40   47   72
   38   66   69   86   25   82
   36   73   76   72   28   91



In [47]:
% Sub-setting 'matrx' to create two sqare matrix

sqmat1 = matrx(:,1:4)
sqmat2 = matrx(:,3:6)

sqmat1 =

   24   52   66   85
   44   57   53   40
   38   66   69   86
   36   73   76   72

sqmat2 =

   66   85   15   79
   53   40   47   72
   69   86   25   82
   76   72   28   91



#### Size of a Matrix :

To get the size of the matrix :

In [48]:
size(matrx)

ans =

   4   6



In [55]:
% To get the number of rows in a matrix :

size(matrx,1)

ans =  4


In [54]:
% To get the number of columns in a matrix :

size(matrx,2)

ans =  6


#### Length of a Matrix

The `length()` function gives the maximum dimension of the matrix as its output. 

So, for a $(4 \times 6)$ matrix, it executes the number of columns as output and for a $(6 \times 4)$ matrix, it executes the number of rows as output.

In [53]:
% Finding length of 'matrx' (maximum dimension):

length(matrx)

ans =  6


> ***Note :***The `length()` function returns the dimension of a vector and for an array, it returns the number of elements present in it.

#### Reshaping of a Matrix

Reshaping of a matrix refers to the manipulation of rows and column of matrix to give it some desired shape.

So, we can reshape our $(6 \times 4)$ matrix named `matrx` into a $(4 \times 6)$ matrix as follows :

In [57]:
% Viewing the origina (4 X 6) matrix :
matrx

% Reshaping the matrix
reshape(matrx, 6,4)

matrx =

   24   52   66   85   15   79
   44   57   53   40   47   72
   38   66   69   86   25   82
   36   73   76   72   28   91

ans =

   24   66   85   25
   44   73   40   28
   38   66   86   79
   36   53   72   72
   52   69   15   82
   57   76   47   91



> ***Note:*** The above reshape operation don't transpose the the matrix rather it just stacks the matrix elements to provide the desired dimension

Similarly, we can make a column matrix (vector) from the $(4 \times 6)$ matrix as follows :

In [58]:
vec = reshape(matrx, 24, 1);

% or,

vec = reshape(matrx, 4*6, 1)

vec =

   24
   44
   38
   36
   52
   57
   66
   73
   66
   53
   69
   76
   85
   40
   86
   72
   15
   47
   25
   28
   79
   72
   82
   91



To make a row-matrix (array) from the $(4 \times 6)$ matrix :

In [59]:
arr = reshape(matrx, 1, 24);

% or,

arr = reshape(matrx, 1, 4*6)

arr =

 Columns 1 through 16:

   24   44   38   36   52   57   66   73   66   53   69   76   85   40   86   72

 Columns 17 through 24:

   15   47   25   28   79   72   82   91




#### Statistical Operations on a Matrix

The basic statistical operations that we can perform on a matrix are :

- Finding minimum and maximum values
- Finding mean, variance and standard deviation

To find out minimum/maximum/mean/standard deviation/variance **column-wise** :

In [77]:
% Minimum
min(matrx)

%or

min(matrx,[],1)

ans =

   24   52   53   40   15   72

ans =

   24   52   53   40   15   72



In [78]:
% Maximum
max(matrx)

% or,

max(matrx,[],1)

ans =

   44   73   76   86   47   91

ans =

   44   73   76   86   47   91



In [79]:
% Mean
mean(matrx)

%or,

mean(matrx,1)

ans =

   35.500   62.000   66.000   70.750   28.750   81.000

ans =

   35.500   62.000   66.000   70.750   28.750   81.000



In [80]:
% Standard Deviation (normalize with N-1)
std(matrx)

%or,
std(matrx,0)

% or,

std(matrx,0,1)

ans =

    8.3865    9.3452    9.6264   21.4690   13.3760    7.8740

ans =

    8.3865    9.3452    9.6264   21.4690   13.3760    7.8740

ans =

    8.3865    9.3452    9.6264   21.4690   13.3760    7.8740



In [76]:
% Standard Deviation (normalize with N)
std(matrx,1)

% or,

std(matrx,1,1)

ans =

    7.2629    8.0932    8.3367   18.5927   11.5839    6.8191

ans =

    7.2629    8.0932    8.3367   18.5927   11.5839    6.8191



In [75]:
% Variance (normalize with N-1)
var(matrx)

%or,
var(matrx,0)

%or,
var(matrx,0,1)

ans =

    70.333    87.333    92.667   460.917   178.917    62.000

ans =

    70.333    87.333    92.667   460.917   178.917    62.000

ans =

    70.333    87.333    92.667   460.917   178.917    62.000



In [74]:
% Variance (normalize with N)
var(matrx,1)

% or,

var(matrx,1,1)

ans =

    52.750    65.500    69.500   345.688   134.188    46.500

ans =

    52.750    65.500    69.500   345.688   134.188    46.500



To find out minimum/maximum/mean/standard deviation/variance **row-wise** :

In [82]:
% Minimum
min(matrx,[],2)

ans =

   15
   40
   25
   28



In [83]:
% Maximum
max(matrx,[],2)

ans =

   85
   72
   86
   91



In [84]:
% Mean
mean(matrx,2)

ans =

   53.500
   52.167
   61.000
   62.667



In [85]:
% Standard Deviation (normalize with N-1)
std(matrx,0,2)

ans =

   28.822
   11.479
   24.413
   24.849



In [91]:
% Standard Deviation (normalize with N)
std(matrx,1,2)

ans =

   26.311
   10.479
   22.286
   22.684



In [90]:
% Variance (normalize with N-1)
var(matrx,0,2)

ans =

   830.70
   131.77
   596.00
   617.47



In [89]:
% Variance (normalize with N)
var(matrx,1,2)

ans =

   692.25
   109.81
   496.67
   514.56



To find out minimum/maximum/mean/standard deviation/variance of **diagonal elements**:

In [92]:
% Minimum
min (diag ( matrx ) )

ans =  24


In [93]:
% Maximum
max (diag ( matrx ) )

ans =  72


In [94]:
% Mean
mean (diag ( matrx ) )

ans =  55.500


In [95]:
% Standard Deviation (normalize with N-1)
std (diag ( matrx ) )

ans =  21.977


In [96]:
% Standard Deviation (normalize with N)
std (diag ( matrx ),1 )

ans =  19.033


In [97]:
% Variance (normalize with N-1)
var (diag ( matrx ) )

ans =  483


In [98]:
% Variance (normalize with N)
var (diag ( matrx ),1 )

ans =  362.25


To find out minimum/maximum/mean/standard deviation/variance of **off-diagonal elements**:

In [99]:
% Minimum
min (diag ( flipud ( matrx ) ) )

ans =  36


In [100]:
% Maximum
max (diag ( flipud ( matrx ) ) )

ans =  85


In [101]:
% Mean
mean (diag ( flipud ( matrx ) ) )

ans =  60


In [102]:
% Standard Deviation (normalize with N-1)
std (diag ( flipud ( matrx ) ) )

ans =  20.704


In [103]:
% Standard Deviation (normalize with N)
std (diag ( flipud ( matrx ) ) ,1 )

ans =  17.930


In [104]:
% Variance (normalize with N-1)
var (diag ( flipud ( matrx ) ) )

ans =  428.67


In [105]:
% Variance (normalize with N)
var (diag ( flipud ( matrx ) ) ,1 )

ans =  321.50


To find out minimum/maximum/mean/standard deviation/variance of all the elements in a matrix :

In [106]:
% Minimum
min (reshape (matrx, size(matrx,1) * size(matrx,2),1))

ans =  15


In [107]:
% Maximum
max (reshape (matrx, size(matrx,1) * size(matrx,2),1))

ans =  91


In [108]:
% Mean
mean (reshape (matrx, size(matrx,1) * size(matrx,2),1))

ans =  57.333


In [109]:
% Standard Deviation (normalize with N-1)
std (reshape (matrx, size(matrx,1) * size(matrx,2),1))

ans =  22.243


In [113]:
% Standard Deviation (normalize with N)
std (reshape (matrx, size(matrx,1) * size(matrx,2),1),1)

ans =  21.775


In [110]:
% Variance (normalize with N-1)
var (reshape (matrx, size(matrx,1) * size(matrx,2),1))

ans =  494.75


In [115]:
% Variance (normalize with N)
var (reshape (matrx, size(matrx,1) * size(matrx,2),1),1)

ans =  474.14


#### Arithmetic Operations on a Matrix

The basic arithmetical operations that we can perform on a matrix are :

- Finding sum and product of rows and columns
- Finding cumulative sum and product of rows and columns

To find out sum/product/cumulative sum/cumulative product **column-wise** :

In [116]:
% Column totals
sum (matrx)

% or,
sum (matrx, 1)

ans =

   142   248   264   283   115   324

ans =

   142   248   264   283   115   324



In [117]:
% Product of column elements
prod (matrx)

% or,
prod (matrx,1)

ans =

    1444608   14280552   18343512   21052800     493500   42443856

ans =

    1444608   14280552   18343512   21052800     493500   42443856



In [118]:
% Cumulative Sum (Column-wise)
cumsum (matrx)

% or,
cumsum(matrx,1)

ans =

    24    52    66    85    15    79
    68   109   119   125    62   151
   106   175   188   211    87   233
   142   248   264   283   115   324

ans =

    24    52    66    85    15    79
    68   109   119   125    62   151
   106   175   188   211    87   233
   142   248   264   283   115   324



In [119]:
% Cumulative Product (Column-wise)
cumprod (matrx)

% or,
cumprod (matrx,1)

ans =

         24         52         66         85         15         79
       1056       2964       3498       3400        705       5688
      40128     195624     241362     292400      17625     466416
    1444608   14280552   18343512   21052800     493500   42443856

ans =

         24         52         66         85         15         79
       1056       2964       3498       3400        705       5688
      40128     195624     241362     292400      17625     466416
    1444608   14280552   18343512   21052800     493500   42443856



To find out sum/product/cumulative sum/cumulative product **row-wise** :

In [120]:
% Row totals
sum (matrx, 2)

ans =

   321
   313
   366
   376



In [121]:
% Product of row elements
prod (matrx,2)

ans =

    8296516800
   17992592640
   30509067600
   36641299968



In [122]:
% Cumulative Sum (Row-wise)
cumsum(matrx,2)

ans =

    24    76   142   227   242   321
    44   101   154   194   241   313
    38   104   173   259   284   366
    36   109   185   257   285   376



In [123]:
% Cumulative Product (Row-wise)
cumprod (matrx, 2)

ans =

 Columns 1 through 5:

            24          1248         82368       7001280     105019200
            44          2508        132924       5316960     249897120
            38          2508        173052      14882472     372061800
            36          2628        199728      14380416     402651648

 Column 6:

    8296516800
   17992592640
   30509067600
   36641299968



To find out the sum/product/cumulative sum/cumulative product of all the **diagonal elements** :

In [124]:
% Diagonal totals
sum ( diag( matrx ) )

ans =  222


In [125]:
% Product of diagonal elements
prod ( diag( matrx ) )

ans =  6796224


In [126]:
% Cumulative Sum (Principal diagonal)
cumsum ( diag( matrx ) )

ans =

    24
    81
   150
   222



In [127]:
% Cumulative Product (Principal diagonal)
cumprod ( diag( matrx ) )

ans =

        24
      1368
     94392
   6796224



To find out the sum/product/cumulative sum/cumulative product of all the **off-diagonal elements** :

In [128]:
% Off-Diagonal totals
sum ( diag( flipud(matrx) ) )

ans =  240


In [129]:
% Product of off-diagonal elements
prod ( diag( flipud(matrx) ) )

ans =  10703880


In [130]:
% Cumulative Sum (Off diagonal)
cumsum ( diag( flipud(matrx) ) )

ans =

    36
   102
   155
   240



In [131]:
% Cumulative Product (Off diagonal)
cumprod ( diag( flipud(matrx) ) )

ans =

         36
       2376
     125928
   10703880



To find out the sum/product/cumulative sum/cumulative product of **all matrix elements** :

In [132]:
% Sum of all the elements
sum( sum( matrx ) )

% or,
sum (reshape ( matrx, size(matrx,1) * size(matrx,2),1) )

ans =  1376
ans =  1376


In [133]:
% Product of all the elements
prod( prod( matrx ) )

% or,
prod (reshape ( matrx, size(matrx,1) * size(matrx,2),1) )

ans =    1.6687e+41
ans =    1.6687e+41


In [134]:
% Cumulative sum of all the elements when matrix reshaped as a vector
cumsum (reshape ( matrx, size(matrx,1) * size(matrx,2),1))

ans =

     24
     68
    106
    142
    194
    251
    317
    390
    456
    509
    578
    654
    739
    779
    865
    937
    952
    999
   1024
   1052
   1131
   1203
   1285
   1376



In [135]:
% Cumulative product of all the elements when matrix reshaped as a vector
cumprod (reshape ( matrx, size(matrx,1) * size(matrx,2),1))

ans =

   2.4000e+01
   1.0560e+03
   4.0128e+04
   1.4446e+06
   7.5120e+07
   4.2818e+09
   2.8260e+11
   2.0630e+13
   1.3616e+15
   7.2163e+16
   4.9792e+18
   3.7842e+20
   3.2166e+22
   1.2866e+24
   1.1065e+26
   7.9669e+27
   1.1950e+29
   5.6166e+30
   1.4042e+32
   3.9316e+33
   3.1060e+35
   2.2363e+37
   1.8338e+39
   1.6687e+41



#### Logarithimic Operations on a Matrix

The logarithimic operations that can be performed upon a matrix are :

- `logm()` : To find principal logarithm matrix
- `expm()` : This returns $e$ raised to the power of each element or, $x ^ e$

We need square matrix to perform the logarithmic operations, as follows :

In [136]:
% Principal logarithm matrix
logm(sqmat1)

ans =

   1.86267  -0.84131   0.73340   3.12359
   2.05911   4.43094   0.77614  -1.87100
   0.40865   0.20795   2.75590   2.22480
  -0.36169   1.19281   1.48817   3.38982



In [137]:
% To e-power of element
expm(sqmat2)

ans =

   7.8377e+105   8.1001e+105   3.4915e+105   9.6571e+105
   6.9898e+105   7.2238e+105   3.1138e+105   8.6123e+105
   8.4111e+105   8.6928e+105   3.7469e+105   1.0364e+106
   8.6565e+105   8.9463e+105   3.8562e+105   1.0666e+106



#### Exponential Operations on a Matrix

The exponential operations that can be performed upon a matrix are :

- `mpower()` : Its just an alternate way to execute $A^B$,but, it enables operator overloading for classes.
- `sqrtm()` : This returns the principal square root of the matrix $A$, i.e. $X.X = A$.
 
 We need **square matrix** to perform the such exponential operations, as follows :

In [138]:
% Power of matrix
mpower(sqmat1,2)

ans =

    8432   14773   15354   15916
    7018   11955   12622   13458
    9534   16570   17303   17996
    9556   16305   16961   17700



In [139]:
% Principal square root of matrix
sqrtm( sqmat1)

ans =

 Columns 1 through 3:

   2.35426 - 0.13823i   0.94781 - 0.03841i   3.47718 + 0.19503i
   4.05380 + 0.94897i   6.86991 + 0.26369i   3.64758 - 1.33891i
   2.62575 - 1.46439i   3.02978 - 0.40691i   4.40016 + 2.06613i
   0.69009 + 0.60481i   4.36822 + 0.16806i   5.29082 - 0.85334i

 Column 4:

   7.46995 - 0.04487i
  -1.02093 + 0.30805i
   6.50009 - 0.47537i
   6.11414 + 0.19633i



#### Determinant of a Matrix

To get the determinant of a matrix, we use the `det()` :

In [140]:
det(sqmat1)

ans = -252542.00000


#### Transpose of a Matrix

To get the transpose of a matrix :

In [141]:
matrx'

ans =

   24   44   38   36
   52   57   66   73
   66   53   69   76
   85   40   86   72
   15   47   25   28
   79   72   82   91



#### Inverse of a Matrix

The general function to get the inverse of a matrix is `inv()` but, this doesn't work if the matrix is non-invertible/singular.

Therefore, we use `pinv()` function always, to get the inverse of the matrix even if its a singular matrix, i.e., the determinant of the matrix is zero.

In [142]:
% General inverse :
inv(sqmat1)

ans =

   0.0369760   0.0688796  -0.0061891  -0.0745262
  -0.1336491  -0.0810479   0.1054716   0.0768268
   0.1215798   0.0630628  -0.1471438  -0.0028114
  -0.0113169  -0.0188325   0.0514766  -0.0237743



In [143]:
% Global inverse:
Global_inverse = pinv(sqmat1)

Global_inverse =

   0.0369760   0.0688796  -0.0061891  -0.0745262
  -0.1336491  -0.0810479   0.1054716   0.0768268
   0.1215798   0.0630628  -0.1471438  -0.0028114
  -0.0113169  -0.0188325   0.0514766  -0.0237743



#### Eigen Values & Eigen Vectors of a Matrix

To get the eigen values and eigen vectors of a matrix, we use the `eig()` as follows :

In [144]:
eig (sqmat1)

ans =

   235.9346 +   0.0000i
    -4.1162 +  13.0680i
    -4.1162 -  13.0680i
    -5.7021 +   0.0000i



#### Matrix Addition, Subtraction & Multiplication

In [145]:
% To add two matrices :

mat_add = sqmat1 + sqmat2

mat_add =

    90   137    81   164
    97    97   100   112
   107   152    94   168
   112   145   104   163



In [147]:
% To subtract two matrices :

mat_sub = sqmat1 - sqmat2

mat_sub =

  -42  -33   51    6
   -9   17    6  -32
  -31  -20   44    4
  -40    1   48  -19



In [148]:
% To perform matrix multiplication :

mat_mult = sqmat1 * sqmat2

mat_mult =

   15354   15916    6834   18787
   12622   13458    5784   15566
   17303   17996    7805   21238
   16961   17700    7887   20884



#### Elementwise Matrix Multiplication & Division

In [149]:
% To perform element wise matrix multiplication :

mat_ele_mult = sqmat1 .* sqmat2

mat_ele_mult =

   1584   4420    990   6715
   2332   2280   2491   2880
   2622   5676   1725   7052
   2736   5256   2128   6552



In [150]:
% To perform element wise matrix division :

mat_ele_div = sqmat1 ./ sqmat2

mat_ele_div =

   0.36364   0.61176   4.40000   1.07595
   0.83019   1.42500   1.12766   0.55556
   0.55072   0.76744   2.76000   1.04878
   0.47368   1.01389   2.71429   0.79121

